### PR TITLE
Pass encrypt feature

### LINKED ISSUE #33: [Task] Hash/Encrypt login credentials
**Description**
Encrypt via hashing the user credentials for login/sign-up

**Additional Information**
- Password should be encrypted on back-end with a black-box algorithm

### PR DESCRIPTION
**Pull request by Pyxsys**
Added password encryption.
Changes were tested via postman and react front-end on both local and docker systems.

**linked issues**:
 closes #33

### CODE REVIEW

**Comment by Pyxsys** [comment]
please test and ensure encryption works on your end before approving.

**Review by NathanZiri — APPROVED** [review]
looks good

**Comment by SekayZ** [comment]
Works fine!

**Review by SekayZ — APPROVED** [review]
Works fine!

**Review by nirmal864 — APPROVED** [review]
Works well

**Pull request merged**
