### PR TITLE
Travis introduction

### PR DESCRIPTION
**Pull request by SekayZ**
Pull request created to test TravisCI

### CODE REVIEW

**Review by Pyxsys — CHANGES_REQUESTED** [review]
Rejecting PR. 
1. Travis not satisfied.
2. Should be merged into BE_PreProd first.

**Comment by SekayZ** [comment]
- Travis is satisfied
- Changed merging to BE_PreProd

**Review by NathanZiri — COMMENTED** [review]
Great Stuff, looks good

**Review by Pyxsys — APPROVED** [review]
Travis appeased, and merging into good branch. Thumbs up!

**Comment by Pyxsys** [comment]
closes #82.
closes #83.

**Pull request merged**
